# Generated by Django 2.2.16 on 2021-02-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BPTLAppId",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_id",
                    models.URLField(
                        help_text="A (globally) unique ID of the BPTL application. In this case the URL that points to the appropriateapplication on the Openzaak Autorisaties API.",
                        verbose_name="BPTL Application ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable application identifier.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
            ],
            options={
                "verbose_name": "BPTL Application ID",
            },
        ),
    ]
