# Generated by Django 2.2.16 on 2020-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganisatieOnderdeel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "organisatie-onderdeel",
                "verbose_name_plural": "organisatie-onderdelen",
            },
        ),
    ]
