# Generated by Django 2.2.16 on 2020-09-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisatieonderdelen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisatieonderdeel",
            name="slug",
            field=models.SlugField(max_length=24, unique=True, verbose_name="slug"),
        ),
    ]
