# Generated by Django 2.2.24 on 2021-06-30 13:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "query",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="search query"
                    ),
                ),
            ],
            options={
                "verbose_name": "search report",
                "verbose_name_plural": "search reports",
            },
        ),
    ]
