# Generated by Django 2.2.20 on 2021-06-01 15:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "query",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="search query"
                    ),
                ),
                ("fields", models.TextField(verbose_name="fields")),
                (
                    "zaaktypen",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=50, verbose_name="zaaktype identification"
                        ),
                        default=list,
                        size=None,
                        verbose_name="zaaktypen",
                    ),
                ),
            ],
            options={
                "verbose_name": "search report",
                "verbose_name_plural": "search reports",
            },
        ),
    ]
