# Generated by Django 3.2.12 on 2022-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elasticsearch", "0002_alter_searchreport_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchreport",
            name="query",
            field=models.JSONField(verbose_name="search query"),
        ),
    ]
