version: '3.8'

services:
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  es_data:
