language: python

python: "3.7"

services:
  - postgresql
  - redis-server
  - docker
  - elasticsearch

addons:
  postgresql: "10"

env:
  global:
  - DJANGO_SETTINGS_MODULE=zac.conf.ci
  - SECRET_KEY=dummy
  - DB_PASSWORD=
  - DB_USER=postgres
  - IS_HTTPS=no

before_install:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.2-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart

# ElasticSearch takes few seconds to start
before_script:
  - sleep 10

jobs:
  include:
    - stage: Tests / Linting
      name: Django tests
      cache: pip
      install:
        - pip install -r requirements/ci.txt codecov
        - npm ci
        - npm run build
      script:
        - python src/manage.py collectstatic --noinput --link
        - coverage run src/manage.py test src
      after_success:
        - codecov

    - name: Import ordering
      install:
        - pip install isort
      before_script: skip
      script: isort . --check-only --diff

    - name: Code style
      install:
        - pip install black
      before_script: skip
      script: black --check src

    - stage: "Docker image"
      if: fork = false
      name: Docker image build
      services:
        - docker
      install: skip
      script: docker build .
      deploy:
        - provider: script
          script: bin/docker_push.sh latest
          on:
            branch: master

        - provider: script
          script: bin/docker_push.sh $TRAVIS_TAG
          on:
            tags: true
