# Minimal docker-compose to get the service up.
# Note that this is NOT meant for real "production" deployments, but only to get up
# and running quickly in a dev environment.
version: '3.4'

services:
  db:
    image: postgres:11-alpine
    # environment:
    #   - POSTGRES_USER=${PG_USER:zac}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:zac}

  redis:
    image: redis:5-alpine

  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
     environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     ports:
       - 9200:9200
       - 9300:9300

  web:
    image: scrumteamzgw/zaakafhandelcomponent
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=zac.conf.docker
      - SECRET_KEY=${SECRET_KEY:-kvilzgj7=*hi*1$$nf2p-%&r*(@83q^wkdkb^^y#!(yaw=8_o!-}
      - IS_HTTPS=0
      - ALLOWED_HOSTS=localhost
      - REDIS_HOST=redis
      - ES_HOST=elasticsearch
      - USE_REDIS_CACHE=True
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - CACHE_OAS=redis:6379/1
      - CACHE_SESSIONS=redis:6379/1
      # - DB_HOST=/var/run/postgresql
    # volumes:
    #   - /var/run/postgresql:/var/run/postgresql
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - elasticsearch
