# Generated by Django 2.2.12 on 2020-06-09 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAdvice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.URLField(
                        help_text="URL reference to the source document in the Documents API. May include the 'versie' querystring parameter.",
                        verbose_name="document URL",
                    ),
                ),
                (
                    "source_version",
                    models.PositiveSmallIntegerField(verbose_name="source version"),
                ),
                (
                    "advice_version",
                    models.PositiveSmallIntegerField(verbose_name="source version"),
                ),
                (
                    "advice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="advices.Advice"
                    ),
                ),
            ],
            options={
                "verbose_name": "document advice",
                "verbose_name_plural": "document advices",
            },
        ),
    ]
