# Generated by Django 2.2.12 on 2020-06-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advices", "0003_auto_20200609_1418"),
    ]

    operations = [
        migrations.RemoveField(model_name="documentadvice", name="advice",),
        migrations.DeleteModel(name="Advice",),
        migrations.DeleteModel(name="DocumentAdvice",),
    ]
