# Generated by Django 2.2.12 on 2020-06-05 15:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserTaskCallback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("callback_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("task_id", models.UUIDField(verbose_name="user task ID")),
                ("callback_received", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "user task callback",
                "verbose_name_plural": "user task callbacks",
            },
        ),
    ]
