# Generated by Django 2.2.12 on 2020-07-29 13:59
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kownsl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kownslconfig",
            name="service",
            field=models.ForeignKey(
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zgw_consumers.Service",
            ),
        ),
    ]
