# Generated by Django 3.2.12 on 2022-08-19 07:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CamundaStartProcess",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "zaaktype_catalogus",
                    models.URLField(
                        help_text="URL-reference to the CATALOGUS of the ZAAKTYPE.",
                        max_length=1000,
                        verbose_name="CATALOGUS of ZAAKTYPE",
                    ),
                ),
                (
                    "zaaktype_identificatie",
                    models.CharField(
                        help_text="`identificatie` of the ZAAKTYPE.",
                        max_length=80,
                        verbose_name="identificatie",
                    ),
                ),
                (
                    "process_definition_key",
                    models.CharField(
                        help_text="Key of camunda process definition linked to this form.",
                        max_length=100,
                        unique=True,
                        verbose_name="process definition key",
                    ),
                ),
            ],
            options={
                "verbose_name": "camunda start process form",
                "verbose_name_plural": "camunda start process forms",
                "unique_together": {("zaaktype_catalogus", "zaaktype_identificatie")},
            },
        ),
        migrations.CreateModel(
            name="ProcessRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="",
                        help_text="The label that will be shown.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="A boolean flag to indicate if a value is required.",
                        verbose_name="required",
                    ),
                ),
                (
                    "roltype_omschrijving",
                    models.CharField(
                        blank=True,
                        help_text="Description of ROLTYPE associated to ROL.",
                        max_length=100,
                        verbose_name="ROLTYPE omschrijving",
                    ),
                ),
                (
                    "betrokkene_type",
                    models.CharField(
                        choices=[
                            ("natuurlijk_persoon", "Natuurlijk persoon"),
                            ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                            ("vestiging", "Vestiging"),
                            ("organisatorische_eenheid", "Organisatorische eenheid"),
                            ("medewerker", "Medewerker"),
                        ],
                        help_text="Betrokkene type of ROL.",
                        max_length=24,
                        verbose_name="betrokkene type",
                    ),
                ),
                (
                    "camunda_start_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="start_process.camundastartprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process ROL",
                "verbose_name_plural": "Process ROLlen",
            },
        ),
        migrations.CreateModel(
            name="ProcessRolChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="",
                        help_text="The label that will be shown.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The value that will be used internally.",
                        max_length=100,
                        verbose_name="value",
                    ),
                ),
                (
                    "process_rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="start_process.processrol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process ROL choice",
                "verbose_name_plural": "Process ROL choices",
            },
        ),
        migrations.CreateModel(
            name="ProcessInformatieObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="",
                        help_text="The label that will be shown.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="A boolean flag to indicate if a value is required.",
                        verbose_name="required",
                    ),
                ),
                (
                    "informatieobjecttype_omschrijving",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="INFORMATIEOBJECTTYPE description",
                    ),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=False,
                        help_text="A boolean flag to indicate whether a user is allowed to add more than 1 document.",
                        verbose_name="Allow multiple documents",
                    ),
                ),
                (
                    "camunda_start_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="start_process.camundastartprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process INFORMATIEOBJECT",
                "verbose_name_plural": "Process INFORMATIEOBJECTen",
            },
        ),
        migrations.CreateModel(
            name="ProcessEigenschap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="",
                        help_text="The label that will be shown.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="A boolean flag to indicate if a value is required.",
                        verbose_name="required",
                    ),
                ),
                (
                    "eigenschapnaam",
                    models.CharField(
                        blank=True,
                        help_text="The name of the EIGENSCHAP",
                        max_length=20,
                        verbose_name="eigenschapnaam",
                    ),
                ),
                (
                    "default",
                    models.CharField(
                        blank=True,
                        help_text="The default value of the ZAAKEIGENSCHAP.",
                        max_length=255,
                        verbose_name="default",
                    ),
                ),
                (
                    "camunda_start_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="start_process.camundastartprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process EIGENSCHAP",
                "verbose_name_plural": "Process EIGENSCHAPpen",
                "unique_together": {("camunda_start_process", "eigenschapnaam")},
            },
        ),
    ]
