# Generated by Django 3.2.12 on 2022-08-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processeigenschap',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='processeigenschap',
            name='camunda_start_process',
        ),
        migrations.RemoveField(
            model_name='processinformatieobject',
            name='camunda_start_process',
        ),
        migrations.RemoveField(
            model_name='processrol',
            name='camunda_start_process',
        ),
        migrations.RemoveField(
            model_name='processrolchoice',
            name='process_rol',
        ),
        migrations.DeleteModel(
            name='CamundaStartProcess',
        ),
        migrations.DeleteModel(
            name='ProcessEigenschap',
        ),
        migrations.DeleteModel(
            name='ProcessInformatieObject',
        ),
        migrations.DeleteModel(
            name='ProcessRol',
        ),
        migrations.DeleteModel(
            name='ProcessRolChoice',
        ),
    ]
