# Generated by Django 3.2.12 on 2022-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinformatieobject',
            name='allow_multiple',
            field=models.BooleanField(default=True, help_text='A boolean flag to indicate whether a user is allowed to add more than 1 document.', verbose_name='Allow multiple documents'),
        ),
    ]
