# Generated by Django 3.2.12 on 2022-06-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("start_process", "0002_alter_processinformatieobject_allow_multiple"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processeigenschap",
            name="value",
        ),
        migrations.RemoveField(
            model_name="processinformatieobject",
            name="value",
        ),
        migrations.RemoveField(
            model_name="processrol",
            name="value",
        ),
    ]
