# Generated by Django 3.2.12 on 2022-06-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("start_process", "0003_auto_20220610_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="processinformatieobject",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="A boolean flag to indicate whether the document is required or not.",
                verbose_name="Required",
            ),
        ),
        migrations.AlterField(
            model_name="processeigenschap",
            name="default",
            field=models.CharField(
                blank=True,
                help_text="The default value of the ZAAKEIGENSCHAP.",
                max_length=255,
                verbose_name="default",
            ),
        ),
        migrations.AlterField(
            model_name="processrol",
            name="default",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A default value of the ROL betrokkene.",
                max_length=255,
                verbose_name="default",
            ),
        ),
        migrations.CreateModel(
            name="ProcessRolChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label that will be shown.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The value that will be used internally.",
                        max_length=100,
                        verbose_name="value",
                    ),
                ),
                (
                    "process_rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="start_process.processrol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process rol choice",
                "verbose_name_plural": "Process rol choices",
            },
        ),
    ]
