# Generated by Django 3.2.12 on 2022-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start_process", "0004_auto_20220621_1358"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processeigenschapchoice",
            options={
                "verbose_name": "Process EIGENSCHAP choice",
                "verbose_name_plural": "Process EIGENSCHAP choices",
            },
        ),
        migrations.AlterModelOptions(
            name="processrolchoice",
            options={
                "verbose_name": "Process ROL choice",
                "verbose_name_plural": "Process ROL choices",
            },
        ),
        migrations.RemoveField(
            model_name="processrol",
            name="default",
        ),
        migrations.AddField(
            model_name="processeigenschap",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="A boolean flag to indicate if a value is required.",
                verbose_name="required",
            ),
        ),
        migrations.AddField(
            model_name="processrol",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="A boolean flag to indicate if a value is required.",
                verbose_name="required",
            ),
        ),
        migrations.AlterField(
            model_name="processeigenschap",
            name="eigenschapnaam",
            field=models.CharField(
                blank=True,
                help_text="The name of the EIGENSCHAP",
                max_length=20,
                verbose_name="eigenschapnaam",
            ),
        ),
        migrations.AlterField(
            model_name="processeigenschap",
            name="label",
            field=models.CharField(
                default="",
                help_text="The label that will be shown.",
                max_length=100,
                verbose_name="label",
            ),
        ),
        migrations.AlterField(
            model_name="processeigenschapchoice",
            name="label",
            field=models.CharField(
                default="",
                help_text="The label that will be shown.",
                max_length=100,
                verbose_name="label",
            ),
        ),
        migrations.AlterField(
            model_name="processinformatieobject",
            name="informatieobjecttype_omschrijving",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="INFORMATIEOBJECTTYPE description",
            ),
        ),
        migrations.AlterField(
            model_name="processinformatieobject",
            name="label",
            field=models.CharField(
                default="",
                help_text="The label that will be shown.",
                max_length=100,
                verbose_name="label",
            ),
        ),
        migrations.AlterField(
            model_name="processrol",
            name="label",
            field=models.CharField(
                default="",
                help_text="The label that will be shown.",
                max_length=100,
                verbose_name="label",
            ),
        ),
        migrations.AlterField(
            model_name="processrol",
            name="roltype_omschrijving",
            field=models.CharField(
                blank=True,
                help_text="Description of ROLTYPE associated to ROL.",
                max_length=100,
                verbose_name="ROLTYPE omschrijving",
            ),
        ),
        migrations.AlterField(
            model_name="processrolchoice",
            name="label",
            field=models.CharField(
                default="",
                help_text="The label that will be shown.",
                max_length=100,
                verbose_name="label",
            ),
        ),
    ]
