# Generated by Django 3.2.12 on 2022-06-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start_process", "0005_auto_20220622_1312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processinformatieobject",
            name="allow_multiple",
            field=models.BooleanField(
                default=False,
                help_text="A boolean flag to indicate whether a user is allowed to add more than 1 document.",
                verbose_name="Allow multiple documents",
            ),
        ),
    ]
