# Generated by Django 3.2.12 on 2022-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start_process", "0006_alter_processinformatieobject_allow_multiple"),
    ]

    operations = [
        migrations.AddField(
            model_name="processeigenschap",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processinformatieobject",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processrol",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
