# Generated by Django 3.2.12 on 2022-07-22 09:47

from django.db import migrations


def set_order_to_pk(apps, _):
    ProcessEigenschap = apps.get_model("start_process", "ProcessEigenschap")
    ProcessInformatieObject = apps.get_model("start_process", "ProcessInformatieObject")
    ProcessRol = apps.get_model("start_process", "ProcessRol")

    for obj in ProcessEigenschap.objects.all():
        obj.order = obj.pk
        obj.save()

    for obj in ProcessInformatieObject.objects.all():
        obj.order = obj.pk
        obj.save()

    for obj in ProcessRol.objects.all():
        obj.order = obj.pk
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("start_process", "0007_auto_20220722_0947"),
    ]

    operations = [
        migrations.RunPython(set_order_to_pk, migrations.RunPython.noop),
    ]
