# Generated by Django 3.2.12 on 2022-07-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("start_process", "0008_auto_20220722_0947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processinformatieobject",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="A boolean flag to indicate if a value is required.",
                verbose_name="required",
            ),
        ),
    ]
