# Generated by Django 3.2.12 on 2022-08-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("start_process", "0010_alter_processeigenschap_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessEigenschapChoice",
        ),
        migrations.DeleteModel(
            name="ProcessRolChoice",
        ),
    ]
