# Generated by Django 2.2.5 on 2020-04-06 09:32

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, verbose_name="naam")),
            ],
            options={
                "verbose_name": "entitlement",
                "verbose_name_plural": "entitlements",
            },
        ),
        migrations.CreateModel(
            name="PermissionSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="naam"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="List of permissions given by this role.",
                        size=None,
                        verbose_name="permissions",
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        help_text="All permissions selected are scoped to this zaaktype.",
                        verbose_name="zaaktype",
                    ),
                ),
                (
                    "max_va",
                    models.CharField(
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        default="openbaar",
                        help_text="Spans Zaken until and including this vertrouwelijkheidaanduiding.",
                        max_length=100,
                        verbose_name="maximale vertrouwelijkheidaanduiding",
                    ),
                ),
            ],
            options={
                "verbose_name": "permission set",
                "verbose_name_plural": "permission sets",
            },
        ),
        migrations.CreateModel(
            name="UserEntitlement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(null=True, verbose_name="start")),
                ("end", models.DateTimeField(null=True, verbose_name="end")),
                (
                    "entitlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.Entitlement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entitlement",
            name="permission_sets",
            field=models.ManyToManyField(
                help_text="Selecting multiple sets makes them add/merge all the permissions together.",
                to="accounts.PermissionSet",
                verbose_name="permission sets",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="entitlements",
            field=models.ManyToManyField(
                blank=True,
                through="accounts.UserEntitlement",
                to="accounts.Entitlement",
            ),
        ),
    ]
