# Generated by Django 2.2.24 on 2021-07-30 15:06

import django.contrib.postgres.fields
from django.db import migrations, models


def remove_blueprint_permissions(apps, _):
    # there is no point in blueprint permissions before roles are defined
    BlueprintPermission = apps.get_model("accounts", "BlueprintPermission")
    BlueprintPermission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role"),
    ]

    operations = [
        migrations.RunPython(remove_blueprint_permissions, migrations.RunPython.noop)
    ]
