# Generated by Django 3.2.12 on 2024-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20240329_1436"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userauthorizationprofile",
            options={
                "verbose_name": "user-authorization profile",
                "verbose_name_plural": "user-authorization profiles",
            },
        ),
        migrations.AddConstraint(
            model_name="userauthorizationprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "auth_profile", "is_active"),
                name="unique_active_userauthorizationprofiles",
            ),
        ),
    ]
