# Generated by Django 5.2.10 on 2026-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20240329_1450"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="atomicpermission",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="atomicpermission",
            constraint=models.UniqueConstraint(
                fields=["permission", "object_url"], name="unique_permission_object_url"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blueprintpermission",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="blueprintpermission",
            constraint=models.UniqueConstraint(
                fields=["role", "policy", "object_type"],
                name="unique_role_policy_object_type",
            ),
        ),
    ]
