# Generated by Django 2.2.24 on 2021-08-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_blueprint_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintpermission",
            name="role",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blueprint_permissions",
                to="accounts.Role",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="blueprintpermission",
            unique_together={("role", "policy")},
        ),
        migrations.AlterModelOptions(
            name="blueprintpermission",
            options={
                "ordering": ("role", "policy__zaaktype_omschrijving"),
                "verbose_name": "blueprint permission",
                "verbose_name_plural": "blueprint permissions",
            },
        ),
        migrations.RemoveField(
            model_name="blueprintpermission",
            name="permission",
        ),
    ]
