# Generated by Django 2.2.24 on 2021-08-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_uuid"),
        ("accounts", "0005_auto_20210803_1420"),
    ]

    operations = []
