# Generated by Django 2.2.24 on 2021-08-17 15:01

from django.db import migrations
import uuid


def generate_uuid(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for row in User.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_20210817_1408"),
    ]

    operations = [
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
    ]
