# Generated by Django 2.2.12 on 2020-04-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20200429_0801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="catalogus",
            field=models.URLField(
                blank=True,
                help_text="Zaaktypencatalogus waarin de zaaktypen voorkomen.",
                verbose_name="catalogus",
            ),
        ),
    ]
