# Generated by Django 2.2.24 on 2021-08-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20210817_1501"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("use_scim", "Can use the SCIM endpoints")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
