# Generated by Django 2.2.24 on 2021-08-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auto_20210824_1039"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blueprintpermission",
            options={
                "ordering": ("role", "object_type", "policy__zaaktype_omschrijving"),
                "verbose_name": "blueprint permission",
                "verbose_name_plural": "blueprint permissions",
            },
        ),
    ]
