# Generated by Django 2.2.12 on 2020-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_accessrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="zaak",
            field=models.URLField(
                help_text="URL reference to the zaak in its API",
                max_length=1000,
                verbose_name="zaak",
            ),
        ),
    ]
