# Generated by Django 2.2.24 on 2021-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("accounts", "0010_auto_20210824_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="manages_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="manager",
                to="auth.Group",
                verbose_name="manages groups",
            ),
        ),
    ]
