# Generated by Django 2.2.24 on 2021-12-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_manages_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atomicpermission",
            name="object_type",
            field=models.CharField(
                choices=[("zaak", "zaak"), ("document", "document")],
                help_text="Type of the objects this permission applies to",
                max_length=50,
                verbose_name="object type",
            ),
        ),
        migrations.AlterField(
            model_name="blueprintpermission",
            name="object_type",
            field=models.CharField(
                choices=[("zaak", "zaak"), ("document", "document")],
                help_text="Type of the objects this permission applies to",
                max_length=50,
                verbose_name="object type",
            ),
        ),
    ]
