# Generated by Django 2.2.16 on 2020-09-23 14:32
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisatieonderdelen", "0002_auto_20200923_1400"),
        ("accounts", "0012_auto_20200917_0831"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizationprofile",
            name="oo",
            field=models.ForeignKey(
                blank=True,
                help_text="Limit access to data belonging to this OO.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisatieonderdelen.OrganisatieOnderdeel",
                verbose_name="organisatieonderdeel",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="oos",
            field=models.ManyToManyField(
                blank=True,
                help_text="The (one or multiple) OOs this user belongs to. Usually this should only be a single OO, but exceptions are possible. User OOs are used in access control checks to zaken.",
                to="organisatieonderdelen.OrganisatieOnderdeel",
                verbose_name="organisatieonderdelen",
            ),
        ),
    ]
