# Generated by Django 2.2.24 on 2021-12-03 07:57

from django.db import migrations


def delete_search_report_blueprint_permissions(apps, _):
    BlueprintPermission = apps.get_model("accounts", "BlueprintPermission")
    BlueprintPermission.objects.filter(object_type="search_report").delete()

def delete_search_report_atomic_permissions(apps, _):
    AtomicPermission = apps.get_model("accounts", "AtomicPermission")
    AtomicPermission.objects.filter(object_type="search_report").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_auto_20211201_1456"),
    ]

    operations = [
        migrations.RunPython(
            delete_search_report_blueprint_permissions, migrations.RunPython.noop
        ),
        migrations.RunPython(
            delete_search_report_atomic_permissions, migrations.RunPython.noop
        )
    ]
