# Generated by Django 2.2.16 on 2020-09-25 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_auto_20200917_0831"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionset",
            name="informatieobjecttype_catalogus",
            field=models.URLField(
                blank=True,
                help_text="Informatieobjecttype catalogus waarin de informatieobjecttypen voorkomen.",
                verbose_name="informatieobjecttype catalogus",
            ),
        ),
        migrations.AddField(
            model_name="permissionset",
            name="informatieobjecttype_omschrijving",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Specifies which document types within the case can be viewed. If left empty, all documents in the case can be viewed.",
                size=None,
                verbose_name="informatieobjecttype omschrijving",
            ),
        ),
        migrations.AddField(
            model_name="permissionset",
            name="informatieobjecttype_va",
            field=models.CharField(
                choices=[
                    ("openbaar", "Openbaar"),
                    ("beperkt_openbaar", "Beperkt openbaar"),
                    ("intern", "Intern"),
                    ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                    ("vertrouwelijk", "Vertrouwelijk"),
                    ("confidentieel", "Confidentieel"),
                    ("geheim", "Geheim"),
                    ("zeer_geheim", "Zeer geheim"),
                ],
                default="openbaar",
                help_text="Maximum level of confidentiality for the document types in the case.",
                max_length=100,
                verbose_name="informatieobjecttype vertrouwelijkheidaanduiding",
            ),
        ),
    ]
