# Generated by Django 2.2.25 on 2022-02-07 08:50

from django.db import migrations


def migrate_activities_read_to_activiteiten_inzien_in_atomic_permissions(apps, _):
    AtomicPermission = apps.get_model("accounts", "AtomicPermission")

    for ap in AtomicPermission.objects.filter(permission="activities:read"):
        ap.permission = "activiteiten:inzien"
        ap.save()


def migrate_activities_read_to_activiteiten_inzien_in_roles(apps, _):
    Role = apps.get_model("accounts", "Role")

    for role in Role.objects.filter(permissions__contains=["activities:read"]):
        permissions = role.permissions
        permissions.remove("activities:read")
        permissions.append("activiteiten:inzien")
        role.permissions = permissions
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auto_20211203_0757"),
    ]

    operations = [
        migrations.RunPython(
            migrate_activities_read_to_activiteiten_inzien_in_atomic_permissions,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            migrate_activities_read_to_activiteiten_inzien_in_roles,
            migrations.RunPython.noop,
        ),
    ]
