# Generated by Django 2.2.16 on 2020-09-24 09:07
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20200923_1446"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="oos",
        ),
        migrations.AlterField(
            model_name="authorizationprofile",
            name="oo",
            field=models.ForeignKey(
                blank=True,
                help_text="Limit access to data belonging to this OO. Leaving this blank means that there is no restriction on OO in place.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisatieonderdelen.OrganisatieOnderdeel",
                verbose_name="organisatieonderdeel",
            ),
        ),
    ]
