# Generated by Django 2.2.25 on 2022-02-21 15:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_update_atomic_permission_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="zaak",
            field=models.URLField(
                help_text="URL-reference to the ZAAK in its API",
                max_length=1000,
                verbose_name="zaak",
            ),
        ),
        migrations.AlterField(
            model_name="blueprintpermission",
            name="policy",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text="Blueprint permission definitions, used to check the access to objects based on their properties i.e. ZAAKTYPE, INFORMATIEOBJECTTYPE",
                verbose_name="policy",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that `username` already exists."
                },
                help_text="Required. 150 characters or fewer.",
                max_length=150,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
