# Generated by Django 2.2.27 on 2022-03-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20220221_1518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useratomicpermission",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("betrokkene", "betrokkene"),
                    ("toegang verlenen", "toegang verlenen"),
                    ("activiteit", "activiteit"),
                    ("adviseur", "adviseur"),
                    ("accordeur", "accordeur"),
                    ("checklist", "checklist"),
                ],
                help_text="The reason why the permission was granted to the user",
                max_length=50,
                verbose_name="reason",
            ),
        ),
    ]
