# Generated by Django 2.2.16 on 2020-10-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20201005_1044"),
        ("accounts", "0015_auto_20200923_1433"),
    ]

    operations = []
