# Generated by Django 3.2.12 on 2022-06-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_auto_20220320_2143"),
    ]
    operations = [
        migrations.AddField(
            model_name="useratomicpermission",
            name="access_request",
            field=models.ForeignKey(
                default=None,
                help_text="Access request that created this permission.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.accessrequest",
            ),
        ),
    ]
