# Generated by Django 2.2.16 on 2020-10-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20200924_0907"),
        ("accounts", "0016_merge_20201006_1355"),
    ]

    operations = []
