# Generated by Django 3.2.12 on 2022-06-08 06:26

from django.db import migrations


def migrate_access_request_to_user_atomic_permission_foreign_key(apps, _):
    AccessRequest = apps.get_model("accounts", "accessrequest")

    for ar in AccessRequest.objects.all():
        user_atomic_permission = ar.user_atomic_permission
        if user_atomic_permission:
            user_atomic_permission.access_request = ar
            user_atomic_permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_auto_20220607_1429"),
    ]

    operations = [
        migrations.RunPython(
            migrate_access_request_to_user_atomic_permission_foreign_key,
            migrations.RunPython.noop,
        ),
    ]
