# Generated by Django 2.2.16 on 2020-10-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_informatieobjecttypepermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permissionset",
            name="informatieobjecttype_catalogus",
        ),
        migrations.RemoveField(
            model_name="permissionset",
            name="informatieobjecttype_max_va",
        ),
        migrations.RemoveField(
            model_name="permissionset",
            name="informatieobjecttype_omschrijvingen",
        ),
    ]
