# Generated by Django 2.2.16 on 2020-10-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_auto_20201014_1509"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="informatieobjecttypepermission",
            unique_together=set(),
        ),
    ]
