# Generated by Django 2.2.16 on 2020-10-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_auto_20201016_1525"),
        ("accounts", "0018_auto_20201012_0818"),
    ]

    operations = []
