# Generated by Django 3.2.12 on 2022-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_auto_20220710_1838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blueprintpermission",
            name="policy",
            field=models.JSONField(
                help_text="Blueprint permission definitions, used to check the access to objects based on their properties i.e. ZAAKTYPE, INFORMATIEOBJECTTYPE",
                verbose_name="policy",
            ),
        ),
    ]
