# Generated by Django 2.2.16 on 2021-03-09 15:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_auto_20210216_1529"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("zaak", "zaak"), ("document", "document")],
                        help_text="Type of the objects this permission applies to",
                        max_length=50,
                        verbose_name="object type",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        help_text="Name of the permission",
                        max_length=255,
                        verbose_name="Permission",
                    ),
                ),
                (
                    "object_url",
                    models.CharField(
                        blank=True,
                        help_text="URL of the object in one of ZGW APIs this permission applies to",
                        max_length=1000,
                        verbose_name="object URL",
                    ),
                ),
                (
                    "policy",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="policy",
                        help_text=(
                            "Blueprint permission definitions, used to check the access to objects based "
                            "on their properties i.e. zaaktype, informatieobjecttype"
                        ),
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Start date of the permission",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="End date of the permission",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
            ],
            options={
                "verbose_name": "permission definition",
                "verbose_name_plural": "permission definitions",
            },
        ),
    ]
