# Generated by Django 3.2.12 on 2022-09-16 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_blueprintpermission_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationToken",
            fields=[
                (
                    "token",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="token",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Name of the person in the organization who can access the API",
                        max_length=200,
                        verbose_name="contact person",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the person, who can access the API",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization which has access to the API",
                        max_length=200,
                        verbose_name="organization",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last date when the token was modified",
                        verbose_name="last modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the token was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Application which has access to the API",
                        max_length=200,
                        verbose_name="application",
                    ),
                ),
                (
                    "administration",
                    models.CharField(
                        blank=True,
                        help_text="Administration which has access to the API",
                        max_length=200,
                        verbose_name="administration",
                    ),
                ),
                (
                    "has_all_reading_rights",
                    models.BooleanField(
                        default=False, verbose_name="has all reading rights"
                    ),
                ),
            ],
            options={
                "verbose_name": "application token authorization",
                "verbose_name_plural": "application token authorizations",
            },
        ),
        migrations.CreateModel(
            name="ApplicationTokenAuthorizationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="start"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="end"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.applicationtoken",
                    ),
                ),
                (
                    "auth_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.authorizationprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="applicationtoken",
            name="auth_profiles",
            field=models.ManyToManyField(
                blank=True,
                through="accounts.ApplicationTokenAuthorizationProfile",
                to="accounts.AuthorizationProfile",
            ),
        ),
    ]
