# Generated by Django 3.2.12 on 2023-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_auto_20220916_0810"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recently_viewed",
            field=models.CharField(
                default="",
                help_text="A list of recently viewed ZAAKs.",
                max_length=1000,
                verbose_name="recently viewed ZAAKs",
            ),
        ),
    ]
