# Generated by Django 2.2.16 on 2021-03-17 11:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_auto_20210309_1810"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissiondefinition",
            name="policy",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text="Blueprint permission definitions, used to check the access to objects based on their properties i.e. zaaktype, informatieobjecttype",
                verbose_name="policy",
            ),
        ),
        migrations.AlterField(
            model_name="permissiondefinition",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Start date of the permission",
                verbose_name="start date",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="permission_definitions",
            field=models.ManyToManyField(
                limit_choices_to={"policy": {}},
                related_name="users",
                to="accounts.PermissionDefinition",
                verbose_name="permission definitions",
            ),
        ),
        migrations.AddConstraint(
            model_name="permissiondefinition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            models.Q(_negated=True, policy={}), ("object_url", "")
                        ),
                        models.Q(
                            models.Q(_negated=True, object_url=""), ("policy", {})
                        ),
                        _connector="OR",
                    )
                ),
                name="check_permission_type",
            ),
        ),
    ]
