# Generated by Django 3.2.12 on 2023-03-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_user_recently_viewed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="recently_viewed",
        ),
    ]
