# Generated by Django 3.2.12 on 2023-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_remove_user_recently_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recently_viewed",
            field=models.JSONField(
                default=[],
                help_text="A list of recently viewed ZAAKs.",
                verbose_name="recently viewed ZAAKs",
            ),
        ),
    ]
