# Generated by Django 3.2.12 on 2023-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_user_recently_viewed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="recently_viewed",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of recently viewed ZAAKs.",
                verbose_name="recently viewed ZAAKs",
            ),
        ),
    ]
