# Generated by Django 3.2.12 on 2023-05-04 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_auto_20230504_2038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauthorizationprofile",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(2999, 12, 31, 0, 0, tzinfo=utc),
                verbose_name="end",
            ),
        )
    ]
