# Generated by Django 2.2.16 on 2021-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_migrate_to_blueprint_permission"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="permissiondefinition",
            name="check_permission_type",
        ),
        migrations.RemoveField(
            model_name="authorizationprofile",
            name="permission_definitions",
        ),
        migrations.RemoveField(
            model_name="permissiondefinition",
            name="policy",
        ),
        migrations.AlterField(
            model_name="permissiondefinition",
            name="object_url",
            field=models.CharField(
                help_text="URL of the object in one of ZGW APIs this permission applies to",
                max_length=1000,
                verbose_name="object URL",
            ),
        ),
    ]
