# Generated by Django 3.2.12 on 2023-08-31 12:31


from django.db import migrations
from zds_client.client import ClientError
import logging

logger = logging.getLogger(__name__)


def migrate_to_catalogus_domein(apps, _):
    BlueprintPermission = apps.get_model("accounts", "BlueprintPermission")
    from zac.core.services import fetch_catalogus

    for blueprintpermission in BlueprintPermission.objects.all():
        if "catalogus" in blueprintpermission.policy:
            try:
                blueprintpermission.policy["catalogus"] = fetch_catalogus(
                    blueprintpermission.policy["catalogus"]
                ).domein
                blueprintpermission.save()
            except ClientError:
                logger.warning("Something went wrong with the migration", exc_info=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_auto_20230504_2043"),
    ]

    operations = [
        migrations.RunPython(migrate_to_catalogus_domein),
    ]
