# Generated by Django 2.2.19 on 2021-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_auto_20210325_1647"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PermissionDefinition",
            new_name="AtomicPermission",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="permission_definitions",
            new_name="atomic_permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="atomic_permissions",
            field=models.ManyToManyField(
                related_name="users",
                to="accounts.AtomicPermission",
                verbose_name="atomic permissions",
            ),
        ),
    ]
