# Generated by Django 3.2.12 on 2023-09-05 05:57

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def create_unique_names_authorization_profile(apps, _):
    AuthorizationProfile = apps.get_model("accounts", "AuthorizationProfile")
    id_names = {ap.id: ap.name for ap in AuthorizationProfile.objects.all()}
    names = []
    for id, name in id_names.items():
        if name in names:
            name += "_kopie"
            id_names[id] = name
        names.append(name)

    for ap in AuthorizationProfile.objects.all():
        ap.name = id_names[ap.id]
        ap.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_auto_20230831_1231"),
    ]

    operations = [
        migrations.RunPython(create_unique_names_authorization_profile),
    ]
