# Generated by Django 2.2.19 on 2021-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_auto_20210402_1007"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atomicpermission",
            options={
                "verbose_name": "atomic permission",
                "verbose_name_plural": "atomic permissions",
            },
        ),
        migrations.AlterField(
            model_name="atomicpermission",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("zaak", "zaak"),
                    ("document", "document"),
                    ("report", "report"),
                ],
                help_text="Type of the objects this permission applies to",
                max_length=50,
                verbose_name="object type",
            ),
        ),
        migrations.AlterField(
            model_name="blueprintpermission",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("zaak", "zaak"),
                    ("document", "document"),
                    ("report", "report"),
                ],
                help_text="Type of the objects this permission applies to",
                max_length=50,
                verbose_name="object type",
            ),
        ),
    ]
