# Generated by Django 2.2.19 on 2021-06-03 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_auto_20210603_0825"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="UserAtomicPermission",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "atomicpermission",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.AtomicPermission",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "accounts_user_atomic_permissions",
                    },
                ),
                migrations.AlterField(
                    model_name="user",
                    name="atomic_permissions",
                    field=models.ManyToManyField(
                        related_name="users",
                        through="accounts.UserAtomicPermission",
                        to="accounts.AtomicPermission",
                        verbose_name="atomic permissions",
                    ),
                ),
                migrations.AddField(
                    model_name="useratomicpermission",
                    name="user",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ]
        )
    ]
