# Generated by Django 3.2.12 on 2023-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_alter_authorizationprofile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blueprintpermission",
            name="hashkey",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
