# Generated by Django 3.2.12 on 2023-09-26 08:07

from django.db import migrations, models


def add_value_to_hashkey_blueprint_permission(apps, _):
    BlueprintPermission = apps.get_model("accounts", "BlueprintPermission")
    # add hashkey
    for bp in BlueprintPermission.objects.all():
        bp.save(force_update=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_alter_authorizationprofile_name"),
    ]

    operations = [
        migrations.RunPython(
            add_value_to_hashkey_blueprint_permission, migrations.RunPython.noop
        )
    ]
