# Generated by Django 2.2.19 on 2021-06-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_auto_20210603_0827"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useratomicpermission",
            old_name="atomicpermission",
            new_name="atomic_permission",
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="user_atomic_permission",
            field=models.OneToOneField(
                blank=True,
                help_text="Permission created if the access request is approved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.UserAtomicPermission",
            ),
        ),
        migrations.AddField(
            model_name="useratomicpermission",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="Comment provided by the granter of the permission",
                max_length=1000,
                verbose_name="comment",
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="Comment provided by the requester",
                max_length=1000,
                verbose_name="comment",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="atomic_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="accounts.UserAtomicPermission",
                to="accounts.AtomicPermission",
                verbose_name="atomic permissions",
            ),
        ),
    ]
