# Generated by Django 2.2.19 on 2021-06-04 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_auto_20210603_0837"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessrequest",
            old_name="start_date",
            new_name="requested_date",
        ),
        migrations.RenameField(
            model_name="accessrequest",
            old_name="end_date",
            new_name="handled_date",
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="handled_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the access request was handled",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="requested_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Date when the access request was created",
                verbose_name="requested date",
            ),
        ),
    ]
