# Generated by Django 2.2.24 on 2021-06-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_initial_permission_reason"),
        ("accounts", "0031_auto_20210601_1328"),
    ]

    operations = []
