# Generated by Django 2.2.19 on 2021-06-25 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_initial_permission_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blueprintpermission",
            options={
                "ordering": ("policy__zaaktype_omschrijving", "permission"),
                "verbose_name": "blueprint definition",
                "verbose_name_plural": "blueprint definitions",
            },
        ),
        migrations.AddField(
            model_name="useratomicpermission",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="End date of the permission",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AddField(
            model_name="useratomicpermission",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Start date of the permission",
                verbose_name="start date",
            ),
        ),
    ]
