# Generated by Django 2.2.24 on 2021-07-06 09:30

from django.db import migrations


def add_id_to_email(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    all_users = User.objects.values_list("email").distinct()
    for email in all_users:
        duplicate_users = User.objects.filter(email=email).order_by("id")[1:]

        for duplicate_user in duplicate_users:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_initial_permission_reason"),
    ]

    operations = []
