# Generated by Django 2.2.24 on 2021-06-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_merge_20210628_1232"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blueprintpermission",
            options={
                "ordering": ("policy__zaaktype_omschrijving", "permission"),
                "verbose_name": "blueprint definition",
                "verbose_name_plural": "blueprint definitions",
            },
        ),
    ]
