# Generated by Django 2.2.19 on 2021-06-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_migrate_atomic_permission_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atomicpermission",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="atomicpermission",
            name="start_date",
        ),
    ]
