# Generated by Django 2.2.19 on 2021-07-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_remove_m2m_unique_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blueprintpermission",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="blueprintpermission",
            name="start_date",
        ),
    ]
