# Generated by Django 2.2.19 on 2021-07-02 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_deduplicate_blueprint_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blueprintpermission",
            options={
                "ordering": ("policy__zaaktype_omschrijving", "permission"),
                "verbose_name": "blueprint permission",
                "verbose_name_plural": "blueprint permissions",
            },
        ),
        migrations.AlterField(
            model_name="userauthorizationprofile",
            name="start",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="start"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blueprintpermission",
            unique_together={("permission", "policy")},
        ),
    ]
