# Generated by Django 2.2.24 on 2021-07-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_auto_20210706_1108"),
        ("accounts", "0045_auto_20210702_1240"),
    ]

    operations = []
