# Generated by Django 2.2.24 on 2021-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_merge_20210709_0903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atomicpermission",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("zaak", "zaak"),
                    ("document", "document"),
                    ("search_report", "search report"),
                ],
                help_text="Type of the objects this permission applies to",
                max_length=50,
                verbose_name="object type",
            ),
        ),
        migrations.AlterField(
            model_name="blueprintpermission",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("zaak", "zaak"),
                    ("document", "document"),
                    ("search_report", "search report"),
                ],
                help_text="Type of the objects this permission applies to",
                max_length=50,
                verbose_name="object type",
            ),
        ),
    ]
