# Generated by Django 2.2.27 on 2022-03-13 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "zaak",
                    models.URLField(
                        editable=False,
                        help_text="URL-reference to the ZAAK in its API.",
                        max_length=1000,
                        unique=True,
                        verbose_name="ZAAK-URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "checklist",
                "verbose_name_plural": "checklists",
            },
        ),
        migrations.CreateModel(
            name="ChecklistType",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                        default=uuid.uuid4,
                        editable=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "zaaktype_catalogus",
                    models.URLField(
                        help_text="URL-referentie naar de CATALOGUS van het ZAAKTYPE.",
                        max_length=1000,
                        verbose_name="CATALOGUS of ZAAKTYPE",
                    ),
                ),
                (
                    "zaaktype_omschrijving",
                    models.CharField(
                        help_text="Omschrijving van het ZAAKTYPE.",
                        max_length=80,
                        verbose_name="Omschrijving",
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        help_text="URL-referentie naar het ZAAKTYPE.",
                        max_length=1000,
                        verbose_name="ZAAKTYPE-URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "checklist type",
                "verbose_name_plural": "checklist types",
                "unique_together": {("zaaktype_catalogus", "zaaktype_omschrijving")},
            },
        ),
        migrations.CreateModel(
            name="ChecklistQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "question",
                    models.TextField(
                        max_length=1000, verbose_name="Text of the question"
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        help_text="Order of the questions as they should be presented in the checklist.",
                        unique=True,
                        verbose_name="Order",
                    ),
                ),
                (
                    "checklist_type",
                    models.ForeignKey(
                        help_text="Checklist type related to this question.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="checklists.ChecklistType",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "unique_together": {("question", "checklist_type")},
            },
        ),
        migrations.CreateModel(
            name="ChecklistAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("answer", models.TextField(verbose_name="Answer to the question")),
                (
                    "checklist",
                    models.ForeignKey(
                        help_text="Checklist this answer is related to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="checklists.Checklist",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question this answers.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="checklists.ChecklistQuestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "checklist answer",
                "verbose_name_plural": "checklist answers",
            },
        ),
        migrations.AddField(
            model_name="checklist",
            name="checklist_type",
            field=models.ForeignKey(
                help_text="Type of the checklist.",
                on_delete=django.db.models.deletion.PROTECT,
                to="checklists.ChecklistType",
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="group_assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="Group responsible for managing this checklist.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.Group",
                verbose_name="group assignee",
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="user_assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="Person responsible for managing this checklist.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user assignee",
            ),
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Human readable name of choice"
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=100, verbose_name="Value of choice"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question the choices are related to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checklists.ChecklistQuestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "question choice",
                "verbose_name_plural": "question choices",
                "unique_together": {("question", "name"), ("question", "value")},
            },
        ),
    ]
