# Generated by Django 2.2.27 on 2022-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0004_auto_20220316_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistquestion",
            name="order",
            field=models.PositiveSmallIntegerField(
                help_text="Order of the questions as they should be presented in the checklist.",
                verbose_name="Order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checklistquestion",
            unique_together={
                ("question", "checklist_type"),
                ("checklist_type", "order"),
            },
        ),
    ]
