# Generated by Django 3.2.12 on 2022-09-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0017_auto_20220909_0947"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Checklist",
        ),
        migrations.DeleteModel(
            name="ChecklistAnswer",
        ),
        migrations.DeleteModel(
            name="ChecklistQuestion",
        ),
        migrations.DeleteModel(
            name="ChecklistType",
        ),
        migrations.DeleteModel(
            name="QuestionChoice",
        ),
    ]
