# Generated by Django 2.2.16 on 2020-11-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regiezaken", "0002_auto_20191001_1543"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegieZaakConfiguratie",
        ),
    ]
