def get_zaak_response(zaak: str, zaaktype: str, **kwargs) -> dict:
    response = {
        "url": zaak,
        "uuid": "d781cd1b-f100-4051-9543-153b93299da4",
        "identificatie": "ZAAK-2019-0000000001",
        "bronorganisatie": "517439943",
        "omschrijving": "some zaak",
        "toelichting": "",
        "zaaktype": zaaktype,
        "registratiedatum": "2019-11-15",
        "verantwoordelijkeOrganisatie": "517439943",
        "startdatum": "2019-11-15",
        "einddatum": None,
        "einddatumGepland": None,
        "uiterlijkeEinddatumAfdoening": None,
        "publicatiedatum": None,
        "communicatiekanaal": "",
        "productenOfDiensten": [],
        "vertrouwelijkheidaanduiding": "openbaar",
        "betalingsindicatie": "",
        "betalingsindicatieWeergave": "",
        "laatsteBetaaldatum": None,
        "zaakgeometrie": None,
        "verlenging": {},
        "opschorting": {},
        "selectielijstklasse": "",
        "hoofdzaak": None,
        "deelzaken": [],
        "relevanteAndereZaken": [],
        "eigenschappen": [],
        "status": None,
        "kenmerken": [],
        "archiefnominatie": None,
        "archiefstatus": "nog_te_archiveren",
        "archiefactiedatum": None,
        "resultaat": None,
    }
    response.update(kwargs)
    return response
