# Generated by Django 5.2.10 on 2026-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="boardcolumn",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="boardcolumn",
            constraint=models.UniqueConstraint(
                fields=["board", "slug"], name="unique_board_slug"
            ),
        ),
    ]
