# Generated by Django 2.2.24 on 2021-08-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardcolumn",
            options={
                "ordering": ("board", "order", "slug"),
                "verbose_name": "board column",
                "verbose_name_plural": "board columns",
            },
        ),
        migrations.AlterField(
            model_name="boarditem",
            name="object",
            field=models.URLField(
                db_index=True,
                help_text="URL of the object in one of ZGW APIs this board item relates to",
                verbose_name="object",
            ),
        ),
        migrations.AlterField(
            model_name="boarditem",
            name="object_type",
            field=models.CharField(
                choices=[("zaak", "zaak")],
                default="zaak",
                help_text="Type of the board item",
                max_length=50,
                verbose_name="object type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boarditem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="boarditem",
            name="board",
        ),
    ]
