# Generated by Django 2.2.27 on 2022-03-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0005_auto_20220317_0942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistanswer",
            name="answer",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Answer to the question"
            ),
        ),
    ]
