# Generated by Django 3.2.12 on 2022-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0011_auto_20220710_1838"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklisttype",
            name="zaaktype_identificatie",
            field=models.CharField(
                default="",
                help_text="`identificatie` of ZAAKTYPE.",
                max_length=80,
                verbose_name="Identificatie of ZAAKTYPE",
            ),
        ),
        migrations.AlterField(
            model_name="checklisttype",
            name="zaaktype_catalogus",
            field=models.URLField(
                help_text="URL-reference to CATALOGUS of ZAAKTYPE.",
                max_length=1000,
                verbose_name="CATALOGUS of ZAAKTYPE",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checklistquestion",
            unique_together={("question", "checklisttype")},
        ),
    ]
