# Generated by Django 3.2.12 on 2022-07-21 14:00

from django.db import migrations

from django.db import migrations
from zac.core.services import fetch_zaaktype


def migrate_checklisttype_zt_omschrijving_to_identificatie_and_set_order_to_pk(apps, _):
    # there is no point in blueprint permissions before roles are defined
    ChecklistType = apps.get_model("checklists", "ChecklistType")
    for order, ct in enumerate(ChecklistType.objects.all()):
        zt = fetch_zaaktype(ct.zaaktype)
        ct.zaaktype_identificatie = zt.identificatie
        ct.order = order
        ct.save()


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0012_auto_20220721_1400"),
    ]

    operations = [
        migrations.RunPython(
            migrate_checklisttype_zt_omschrijving_to_identificatie_and_set_order_to_pk,
            migrations.RunPython.noop,
        )
    ]
