# Generated by Django 3.2.12 on 2022-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0013_auto_20220721_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistquestion",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checklisttype",
            unique_together={("zaaktype_catalogus", "zaaktype_identificatie")},
        ),
        migrations.RemoveField(
            model_name="checklisttype",
            name="zaaktype",
        ),
        migrations.RemoveField(
            model_name="checklisttype",
            name="zaaktype_omschrijving",
        ),
    ]
