# Generated by Django 3.2.12 on 2022-07-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0014_auto_20220721_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklisttype",
            name="zaaktype_identificatie",
            field=models.CharField(
                default="",
                help_text="`identificatie` of ZAAKTYPE.",
                max_length=80,
                verbose_name="ZAAKTYPE identificatie",
            ),
        ),
    ]
