# Generated by Django 2.2.5 on 2020-04-06 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20200406_0934"),
    ]

    operations = [
        migrations.RemoveField(model_name="permissionset", name="zaaktype",),
        migrations.AddField(
            model_name="permissionset",
            name="catalogus",
            field=models.URLField(
                default="",
                help_text="Zaaktypencatalogus waarin de zaaktypen voorkomen.",
                verbose_name="catalogus",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permissionset",
            name="zaaktype_identificaties",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="All permissions selected are scoped to these zaaktypen. If left empty, this applies to all zaaktypen.",
                size=None,
            ),
        ),
    ]
