# Generated by Django 2.2.5 on 2020-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20200406_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userentitlement",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end"),
        ),
        migrations.AlterField(
            model_name="userentitlement",
            name="start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="start"),
        ),
    ]
