# Generated by Django 2.2.5 on 2020-04-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20200429_0759"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="entitlements",
            new_name="auth_profiles",
        ),
        migrations.RenameField(
            model_name="userauthorizationprofile",
            old_name="entitlement",
            new_name="auth_profile",
        ),
    ]
