# Generated by Django 2.2.12 on 2020-09-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auto_20200430_1500"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zaak", models.URLField(max_length=255, verbose_name="zaak")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="comment"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("approve", "Approve"), ("reject", "Reject")],
                        max_length=50,
                        verbose_name="result",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
