# Generated by Django 2.2.12 on 2020-09-17 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_auto_20200910_1219"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessrequest",
            name="handler",
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="handlers",
            field=models.ManyToManyField(
                blank=True,
                help_text="users who can provide access to the zaak",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="result",
            field=models.CharField(
                blank=True,
                choices=[("approve", "approved"), ("reject", "rejected")],
                max_length=50,
                verbose_name="result",
            ),
        ),
    ]
