# Generated by Django 2.2.16 on 2020-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auto_20200923_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizationprofile",
            name="name",
            field=models.CharField(
                help_text="Use an easily recognizable name that maps to the function of users.",
                max_length=255,
                verbose_name="naam",
            ),
        ),
    ]
