# Generated by Django 2.2.16 on 2020-09-23 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_set_default_access_request_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessrequest",
            name="handlers",
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="handler",
            field=models.ForeignKey(
                blank=True,
                help_text="user who has handled the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
