# Generated by Django 2.2.16 on 2020-10-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20201005_1044"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permissionset",
            name="informatieobjecttype_catalogus",
        ),
        migrations.RemoveField(
            model_name="permissionset",
            name="informatieobjecttype_max_va",
        ),
        migrations.RemoveField(
            model_name="permissionset",
            name="informatieobjecttype_omschrijvingen",
        ),
        migrations.CreateModel(
            name="InformatieobjecttypePermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalogus",
                    models.URLField(
                        help_text="Informatieobjecttype catalogus waarin de informatieobjecttypen voorkomen.",
                        max_length=1000,
                        verbose_name="catalogus",
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        help_text="Specifies the informatieobjecttype for which to add the permission.",
                        max_length=100,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "max_va",
                    models.CharField(
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        default="openbaar",
                        help_text="Maximum level of confidentiality for the document types in the case.",
                        max_length=100,
                        verbose_name="maximum vertrouwelijkheidaanduiding",
                    ),
                ),
                (
                    "permission_set",
                    models.ForeignKey(
                        help_text="Associated set of permissions for a zaaktype.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.PermissionSet",
                        verbose_name="permission set",
                    ),
                ),
            ],
            options={
                "verbose_name": "informatieobjecttype permission",
            },
        ),
    ]
