# Generated by Django 2.2.16 on 2020-10-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20201006_1552"),
        ("accounts", "0016_merge_20201006_1355"),
    ]

    operations = []
