# Generated by Django 2.2.16 on 2020-10-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_merge_20201012_1236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informatieobjecttypepermission",
            name="omschrijving",
            field=models.CharField(
                blank=True,
                help_text="Specifies the informatieobjecttype for which to add the permission.",
                max_length=100,
                verbose_name="omschrijving",
            ),
        ),
    ]
