# Generated by Django 2.2.16 on 2020-10-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_merge_20201006_1548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizationprofile",
            name="name",
            field=models.CharField(
                help_text="Use an easily recognizable name that maps to the function of users.",
                max_length=255,
                verbose_name="name",
            ),
        ),
    ]
