# Generated by Django 2.2.12 on 2020-08-04 13:45
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaak",
                    models.URLField(
                        help_text="URL reference to the zaak in its API",
                        max_length=1000,
                        verbose_name="zaak URL",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
                (
                    "status",
                    models.CharField(
                        choices=[("on_going", "On-going"), ("finished", "Finished")],
                        default="on_going",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "document",
                    models.URLField(
                        blank=True,
                        help_text="Document in the Documents API.",
                        max_length=1000,
                        verbose_name="document URL",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person responsible for managing this activity.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assignee",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "unique_together": {("zaak", "name")},
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(verbose_name="notes")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.Activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity event",
                "verbose_name_plural": "activity events",
            },
        ),
    ]
