# Generated by Django 2.2.5 on 2020-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KadasterConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locatieserver",
                    models.URLField(
                        default="https://geodata.nationaalgeoregister.nl/locatieserver/v3/",
                        verbose_name="root URL locatieserver",
                    ),
                ),
                (
                    "bag_api",
                    models.URLField(
                        default="https://bag.basisregistraties.overheid.nl/api/v1/",
                        verbose_name="root URL BAG API",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key used for BAG.",
                        max_length=255,
                        verbose_name="API key",
                    ),
                ),
            ],
            options={"verbose_name": "kadasterconfiguratie",},
        ),
    ]
