# Stage 1 -- install dev tools and build bundle
ARG NODE_VERSION
FROM node:$NODE_VERSION-buster-slim

WORKDIR /app

EXPOSE 4200
CMD ["/app/node_modules/.bin/ng", "serve", "zac-ui", "--base-href=/ui/", "--host=0.0.0.0"]
