# Generated by Django 2.2.16 on 2020-11-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kadaster", "0003_auto_20201103_0818"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kadasterconfig",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="kadasterconfig",
            name="bag_api",
        ),
    ]
