from django.urls import path

from .views import (
    RelatedZakenView,
    ZaakDetailView,
    ZaakDocumentsView,
    ZaakEigenschappenView,
    ZaakObjectsView,
    ZaakReviewRequestCompletedView,
    ZaakReviewRequestDetailView,
    ZaakRolesView,
    ZaakStatusesView,
)

urlpatterns = [
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>",
        ZaakDetailView.as_view(),
        name="zaak-detail",
    ),
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>/statuses",
        ZaakStatusesView.as_view(),
        name="zaak-statuses",
    ),
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>/properties",
        ZaakEigenschappenView.as_view(),
        name="zaak-properties",
    ),
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>/documents",
        ZaakDocumentsView.as_view(),
        name="zaak-documents",
    ),
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>/related-cases",
        RelatedZakenView.as_view(),
        name="zaak-related",
    ),
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>/roles",
        ZaakRolesView.as_view(),
        name="zaak-roles",
    ),
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>/objects",
        ZaakObjectsView.as_view(),
        name="zaak-objects",
    ),
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>/review-requests/completed",
        ZaakReviewRequestCompletedView.as_view(),
        name="zaak-review-requests-completed",
    ),
    path(
        "cases/<str:bronorganisatie>/<str:identificatie>/review-requests/detail",
        ZaakReviewRequestDetailView.as_view(),
        name="zaak-review-requests-detail",
    ),
]
