# Generated by Django 2.1.7 on 2019-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('api_type', models.CharField(choices=[('zrc', 'ZRC'), ('ztc', 'ZTC'), ('drc', 'DRC'), ('brc', 'BRC')], max_length=20, verbose_name='type')),
                ('api_root', models.CharField(max_length=255, verbose_name='api root url')),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('secret', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
