# Generated by Django 2.1.7 on 2019-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='api_root',
            field=models.CharField(max_length=255, unique=True, verbose_name='api root url'),
        ),
    ]
