# Generated by Django 2.1.7 on 2019-04-09 12:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190313_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text="Extra configuration that's service-specific", verbose_name='extra configuration'),
        ),
    ]
