# Generated by Django 2.1.7 on 2019-05-14 11:41

from django.db import migrations


def copy_services(apps, _, reverse=False):
    OldService = apps.get_model('config', 'Service')
    NewService = apps.get_model('zgw_consumers', 'Service')

    if reverse:
        OldService, NewService = NewService, OldService

    for service in OldService.objects.all():
        NewService.objects.create(
            label=service.label,
            api_type=service.api_type,
            api_root=service.api_root,
            extra=service.extra,
            client_id=service.client_id,
            secret=service.secret,
        )


def revert_services(apps, _):
    copy_services(apps, _, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_service_extra'),
        ('zgw_consumers', '0003_auto_20190514_1009'),
    ]

    operations = [
        migrations.RunPython(copy_services, revert_services),
    ]
