# Generated by Django 2.2.5 on 2019-09-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_migrate_to_zgw_consumers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
