# Generated by Django 2.2.5 on 2019-09-27 13:43

from django.db import migrations, models
import zac.config.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0005_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegieZaakConfiguratie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the theme/subject', max_length=100)),
                ('zaaktype_main', models.URLField()),
                ('related_zaaktypes', zac.config.models.ZaakTypeArrayField(base_field=models.URLField(), default=[], size=None)),
            ],
            options={
                'verbose_name': 'Regie Zaak',
            },
        ),
    ]
