# Generated by Django 3.2.12 on 2024-03-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingPageConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Startpagina Werkomgeving", max_length=255
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Kies de afbeelding die bovenaan de pagina wordt getoond.",
                        null=True,
                        upload_to="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landingspagina configuratie",
            },
        ),
        migrations.CreateModel(
            name="LandingPageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("icon", models.CharField(max_length=25)),
                (
                    "landing_page_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="landing.landingpageconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landingspagina sectie",
            },
        ),
        migrations.CreateModel(
            name="LandingPageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=25)),
                ("icon", models.CharField(blank=True, max_length=25)),
                ("href", models.CharField(max_length=255)),
                (
                    "landing_page_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="landing.landingpageconfiguration",
                    ),
                ),
                (
                    "landing_page_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="landing.landingpagesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landingspagina link",
            },
        ),
    ]
