# Generated by Django 3.2.12 on 2022-11-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageconfiguration',
            name='image',
            field=models.ImageField(blank=True, help_text='Kies de afbeelding die bovenaan de pagina wordt getoond.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='landingpagelink',
            name='icon',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
