# Generated by Django 3.2.12 on 2024-03-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaObjectTypesConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=True,
                        help_text="Setting to False will allow the user to define custom objecttypes instead of the URL-references retrieved from the list of meta objecttypes from the OBJECTS API.",
                    ),
                ),
                (
                    "meta_list_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the Meta List OBJECTTYPE. This is used to fetch the meta list objecttype for managing meta objects and objecttypes.",
                        verbose_name="URL-reference to MetaListObjectType in OBJECTTYPES API.",
                    ),
                ),
                (
                    "checklist_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the Checklist OBJECTTYPE. This is used to fetch the checklist objecttype for a ZAAK.",
                        verbose_name="URL-reference to Checklist in OBJECTTYPES API.",
                    ),
                ),
                (
                    "checklisttype_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the ChecklistType OBJECTTYPE. This is used to get the questions for a checklist for a ZAAKTYPE.",
                        verbose_name="URL-reference to ChecklistType in OBJECTTYPES API.",
                    ),
                ),
                (
                    "oudbehandelaren_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the Oudbehandelaren OBJECTTYPE. This is used to register the old ROL when the ROL was of ROLTYPE `behandelaar`.",
                        verbose_name="URL-reference to Oudbehandelaren in OBJECTTYPES API.",
                    ),
                ),
                (
                    "review_objecttype",
                    models.URLField(
                        default="",
                        help_text="URL-reference to the review OBJECTTYPE. This is used to register an advice/approval to a review request.",
                        verbose_name="URL-reference to review in OBJECTTYPES API.",
                    ),
                ),
                (
                    "review_request_objecttype",
                    models.URLField(
                        default="",
                        help_text="URL-reference to the review request OBJECTTYPE. This is used to register a review request.",
                        verbose_name="URL-reference to review request in OBJECTTYPES API.",
                    ),
                ),
                (
                    "start_camunda_process_form_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the StartCamundaForms OBJECTTYPE. This is used to set the right variables for the camunda process related to the ZAAKTYPE.",
                        verbose_name="URL-reference to StartCamundaForms in OBJECTTYPES API.",
                    ),
                ),
                (
                    "zaaktype_attribute_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the ZaaktypeAttributes OBJECTTYPE. This is used to get extra data for EIGENSCHAPs.",
                        verbose_name="URL-reference to ZaaktypeAttributes in OBJECTTYPES API.",
                    ),
                ),
            ],
            options={
                "verbose_name": "meta objecttype configuration",
            },
        ),
        migrations.CreateModel(
            name="CoreConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_id",
                    models.URLField(
                        default="",
                        help_text="A (globally) unique ID of the BPTL application. In this case the URL that points to the appropriate application on the Open Zaak Autorisaties API.",
                        verbose_name="BPTL Application ID",
                    ),
                ),
                (
                    "non_sso_login_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="A flag that allows non-SSO login (True) or not (False).",
                        verbose_name="Non-SSO login enabled",
                    ),
                ),
                (
                    "primary_brc",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "brc"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="zgw_consumers.service",
                    ),
                ),
                (
                    "primary_drc",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "drc"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="zgw_consumers.service",
                    ),
                ),
                (
                    "primary_objects_api",
                    models.ForeignKey(
                        help_text="Default OBJECTS API service to use",
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Primary OBJECTS API",
                    ),
                ),
                (
                    "primary_objecttypes_api",
                    models.ForeignKey(
                        help_text="Default OBJECTTYPES API service to use",
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Primary OBJECTTYPES API",
                    ),
                ),
            ],
            options={
                "verbose_name": "global configuration",
            },
        ),
    ]
