# Generated by Django 2.2.20 on 2021-06-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("core", "0003_coreconfig_app_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreconfig",
            name="primary_objects_api",
            field=models.ForeignKey(
                help_text="Default Objects API service to use",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
                verbose_name="Primary objects API",
            ),
        ),
    ]
