# Generated by Django 2.2.25 on 2022-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_coreconfig_primary_objecttypes_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreconfig",
            name="non_adfs_login_enabled",
            field=models.BooleanField(
                default=True,
                help_text="A flag that allows non-ADFS login (True) or not (False).",
                verbose_name="Non-ADFS login enabled",
            ),
        ),
    ]
