# Generated by Django 2.2.25 on 2022-02-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_coreconfig_non_adfs_login_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coreconfig",
            name="app_id",
            field=models.URLField(
                default="",
                help_text="A (globally) unique ID of the BPTL application. In this case the URL that points to the appropriate application on the Open Zaak Autorisaties API.",
                verbose_name="BPTL Application ID",
            ),
        ),
        migrations.AlterField(
            model_name="coreconfig",
            name="primary_objects_api",
            field=models.ForeignKey(
                help_text="Default OBJECTS API service to use",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
                verbose_name="Primary OBJECTS API",
            ),
        ),
        migrations.AlterField(
            model_name="coreconfig",
            name="primary_objecttypes_api",
            field=models.ForeignKey(
                help_text="Default OBJECTTYPES API service to use",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
                verbose_name="Primary OBJECTTYPES API",
            ),
        ),
    ]
