# Generated by Django 3.2.12 on 2022-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20220824_1434"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaObjectTypesConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_camunda_process_form_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the StartCamundaForms OBJECTTYPE. This is used to set the right variables for the camunda process related to the ZAAKTYPE.",
                        verbose_name="URL-reference to StartCamundaForms in OBJECTTYPES API.",
                    ),
                ),
                (
                    "zaaktype_attribute_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the ZaaktypeAttributes OBJECTTYPE. This is used to get extra data for EIGENSCHAPs.",
                        verbose_name="URL-reference to ZaaktypeAttributes in OBJECTTYPES API.",
                    ),
                ),
                (
                    "checklisttype_objecttype",
                    models.URLField(
                        default="",
                        help_text="A URL-reference to the ChecklistType OBJECTTYPE. This is used to get the questions for a checklist for a zaaktype.",
                        verbose_name="URL-reference to ChecklistType in OBJECTTYPES API.",
                    ),
                ),
            ],
            options={
                "verbose_name": "meta objecttype configuration",
            },
        ),
        migrations.RemoveField(
            model_name="coreconfig",
            name="start_camunda_process_form_objecttype",
        ),
        migrations.RemoveField(
            model_name="coreconfig",
            name="zaaktype_attribute_objecttype",
        ),
    ]
