# Generated by Django 3.2.12 on 2022-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20220901_1443"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="checklist_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the Checklist OBJECTTYPE. This is used to fetch the checklist objecttype for a ZAAK.",
                verbose_name="URL-reference to Checklist in OBJECTTYPES API.",
            ),
        ),
        migrations.AlterField(
            model_name="metaobjecttypesconfig",
            name="checklisttype_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the ChecklistType OBJECTTYPE. This is used to get the questions for a checklist for a ZAAKTYPE.",
                verbose_name="URL-reference to ChecklistType in OBJECTTYPES API.",
            ),
        ),
    ]
