# Generated by Django 3.2.12 on 2023-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20220902_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="oudbehandelaren_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the Oudbehandelaren OBJECTTYPE. This is used to register the old ROL when the ROL was of ROLTYPE `behandelaar`.",
                verbose_name="URL-reference to Oudbehandelaren in OBJECTTYPES API.",
            ),
        ),
    ]
