# Generated by Django 3.2.12 on 2024-01-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_metaobjecttypesconfig_oudbehandelaren_objecttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="meta_list_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the Meta List OBJECTTYPE. This is used to fetch the meta list objecttype for managing meta objects and objecttypes.",
                verbose_name="URL-reference to MetaListObjectType in OBJECTTYPES API.",
            ),
        ),
    ]
