# Generated by Django 2.2.27 on 2022-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0003_auto_20220315_1456"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistanswer",
            name="answer",
            field=models.TextField(
                max_length=1000, verbose_name="Answer to the question"
            ),
        ),
        migrations.AlterField(
            model_name="checklistanswer",
            name="question",
            field=models.TextField(max_length=1000, verbose_name="Related question"),
        ),
        migrations.AlterField(
            model_name="checklistquestion",
            name="order",
            field=models.PositiveSmallIntegerField(
                help_text="Order of the questions as they should be presented in the checklist.",
                unique=True,
                verbose_name="Order",
            ),
        ),
    ]
