# Generated by Django 2.2.27 on 2022-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0006_auto_20220320_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistanswer",
            name="document",
            field=models.URLField(
                blank=True,
                help_text="Document in the Documents API.",
                max_length=1000,
                verbose_name="document URL",
            ),
        ),
        migrations.AddField(
            model_name="checklistanswer",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="remarks"),
        ),
        migrations.AlterField(
            model_name="checklistanswer",
            name="answer",
            field=models.TextField(blank=True, verbose_name="Answer to the question"),
        ),
    ]
