# Generated by Django 3.2.12 on 2022-09-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0015_alter_checklisttype_zaaktype_identificatie"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checklistquestion",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="checklisttype",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="questionchoice",
            unique_together=None,
        ),
    ]
