# Generated by Django 2.2.16 on 2020-09-22 15:34
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0010_nlxconfig"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coreconfig",
            options={"verbose_name": "global configuration"},
        ),
        migrations.AddField(
            model_name="coreconfig",
            name="primary_brc",
            field=models.ForeignKey(
                limit_choices_to={"api_type": "brc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
        migrations.AlterField(
            model_name="coreconfig",
            name="primary_drc",
            field=models.ForeignKey(
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
    ]
