# Generated by Django 2.2.24 on 2021-10-08 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0002_auto_20200805_1413"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="assignee",
            new_name="user_assignee",
        ),
        migrations.AddField(
            model_name="activity",
            name="group_assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="Group responsible for managing this activity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.Group",
                verbose_name="group assignee",
            ),
        ),
    ]
