# Generated by Django 2.2.25 on 2022-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_auto_20211104_1407"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="zaak",
            field=models.URLField(
                help_text="URL-reference to the ZAAK in its API",
                max_length=1000,
                verbose_name="ZAAK-URL",
            ),
        ),
    ]
